---
- name: Reload systemd
  systemd:
    daemon_reload: yes
- name: Restart cosmovisor
  systemd:
    name: cosmovisor
    state: restarted
- name: Stop cosmovisor
  systemd:
    name: cosmovisor
    state: stopped
- name: Start cosmovisor
  systemd:
    name: cosmovisor
    state: started
